# Informações sobre uso do Azure Event Hubs com KEDA
# https://keda.sh/docs/2.14/scalers/azure-event-hub/
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: workervotacao-scaledobject
spec:
  scaleTargetRef:
    name: workervotacao
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-eventhub
    metadata:
      connectionFromEnv: AzureEventHubs__EventHubsConnectionString
      storageConnectionFromEnv: AzureEventHubs__BlobStorageConnectionString
      eventHubName: topic-enquete
      consumerGroup: workerenquete
      unprocessedEventThreshold: '10'
      activationUnprocessedEventThreshold: '1'
      blobContainer: blobenquete
      checkpointStrategy: blobMetadata